# PHP
php_memory_limit: "128M"
php_max_execution_time: "120"
php_packages:
  - php5.6
  - php5.6-cli
  - php5.6-common
  - php5.6-mysql
  - php5.6-mcrypt
  - php5.6-json
  - php5.6-gd
  - php5.6-mbstring
  - php5.6-xml
  - php5.6-bcmath
  - php-mysqlnd-ms
php_conf_paths:
  - /etc/php/5.6/apache2
  - /etc/php/5.6/cli

# Teampass
teampass_db: "teampass_db"
teampass_db_user: "teampass_user"
teampass_db_password: "teampass"
teampass_server_name: "teampass.manati.vpn"

# OpenVPN
openvpn_enabled: yes
openvpn_etcdir: /etc/openvpn
openvpn_keydir: "{{openvpn_etcdir}}/keys"

# Default settings (See OpenVPN documentation)
openvpn_host: "manati.vpn"              # The server address
openvpn_port: 1194
openvpn_proto: udp
openvpn_dev: tun
openvpn_server: 10.8.0.0 255.255.255.0
openvpn_max_clients: 20
openvpn_log: /var/log/openvpn.log                   # Log's directory
openvpn_keepalive: "10 120"
openvpn_ifconfig_pool_persist: ipp.txt
openvpn_comp_lzo: yes                               # Enable compression
openvpn_cipher: BF-CBC                              # Encryption algorithm
openvpn_status: openvpn-status.log
openvpn_verb: 3
openvpn_user: nobody
openvpn_group: nogroup
openvpn_resolv_retry: infinite
openvpn_server_options:
  - push "dhcp-option DNS 8.8.8.8"
  - push "redirect-gateway def1 bypass-dhcp"
openvpn_key_country: CR
openvpn_key_province: SJO
openvpn_key_city: SanJose
openvpn_key_org: Manati
openvpn_key_email: kevin@estudiomanati.com
openvpn_key_size: 1024

openvpn_clients: [client]                         # Make clients certificate
openvpn_clients_revoke: []                        # Revoke clients certificates

# Use PAM authentication
openvpn_use_pam: yes
openvpn_use_pam_users: []                         # If empty use system users

# Use simple authentication (default is disabled)
openvpn_simple_auth: yes
openvpn_simple_auth_password: password
