---
- name: Firewall | Allow ssh
  ufw: rule=allow port=ssh proto=tcp

- name: Firewall | Allow openvpn
  ufw: rule=allow port=1194 proto=udp

- name: Firewall | Allow apache on vpn
  ufw: rule=allow port=80 proto=tcp src=10.8.0.0/24 

- name: Firewall | Enable ufw
  ufw: state=enabled
