---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../config.yml

  gather_facts: False
  pre_tasks:
    - include: tasks/init.yml
    - include: tasks/init-debian.yml

  roles:
    # Essential roles.
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql

    # Roles for security and stability on production.
    - geerlingguy.security

    # Teampass role.
    - kporras07.teampass

    # OpenVPN
    - Stouts.openvpn

  tasks:
    - include: tasks/www.yml
    - include: tasks/firewall.yml
