---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../config.yml

  pre_tasks:
    - include: tasks/init-debian.yml

  roles:
    # Essential roles.
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql

    # Roles for security and stability on production.
    - geerlingguy.security

  tasks:
    - include: tasks/www.yml
