---
- src: geerlingguy.apache
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.git
- src: geerlingguy.mysql
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: geerlingguy.security
- src: kporras07.teampass
